### ISSUE TITLE
What LLVM versions are supported?

### ISSUE THREAD

**Issue by zyedidia** [gwsystems/aWsm#104]
Does aWsm support using an LLVM version other than 9? I tried building with LLVM 15, and managed to build the binary but it encounters an immediate segmentation fault when trying to build something. It looks like the crash happens inside `LLVMGetElementType` in `libLLVM-15.so` at `src/codegen/function.rs:172`.

**Comment by emil916** [comment]
Actually, it is specified in the installation script (install_deb), it should install smoothly with version 12. Unsure about any higher versions at this point, so cant comment on that.

**Comment by zyedidia** [comment]
Thanks
