### ISSUE TITLE
mismatch in type_id for function pointer-based calls

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/aWsm#5]
I've been trying to get GOCR compiling and running with silverfish but there seem to be some weirdness around the function pointers. Was able to succesfully compile it.

The call here leads to an assert in the runtime: https://github.com/phanikishoreg/gocr/blob/master/src/list.c#L325

assert triggered in the runtime: https://github.com/gparmer/silverfish/blob/master/runtime/memory/64bit_nix.c#L129

I debugged to see what the assert is and why that is triggered, and this is the log: 
```
$ ./gocr.out -f ASCII < test.pbm 
// log here: "add_function_to_table" <func_index> <func type_id> <func addr>
add_function_to_table 1 3 0x40a760
add_function_to_table 2 1 0x40a7c0
add_function_to_table 3 1 0x40a9a0
add_function_to_table 4 2 0x40ac40
add_function_to_table 5 0 0x40bf10
add_function_to_table 6 2 0x40bf70
add_function_to_table 7 1 0x40bf20
add_function_to_table 8 1 0x40cd70
add_function_to_table 9 1 0x40cda0
add_function_to_table 10 4 0x40ec10
add_function_to_table 11 2 0x53a080        // this seem to be the function..
add_function_to_table 12 4 0x53a180
add_function_to_table 13 4 0x53a150
01 // program output
// log here: "get_function_from_table" <func_idx> <func typeid in indirect table> <type_id param>
get_function_from_table 11 2 5         // called with a different type id 5
get_function_from_table 11 2 5         // second call.. 
$ 
```
The problem is, on function table initialization, the type_id of that function is set to 2. But on call to get_function_from_table, the type_id requested is 5. Unsure how this is happening but this is how far I got with the debugging so far. In the above logs, I've disabled that assert I pointed to and the program works otherwise, outputs "01" that's in the input image.

@Others : I would really appreciate if you can help me fix this. For now, I'm going to just comment out the "type check" assert in the runtime (still keeping the function pointer NULL check).

**Comment by Others** [comment]
Just want to note here that this is aWsm/silverfish detecting undefined behavior in the C program. https://stackoverflow.com/a/559671/1981468

**Comment by Others** [comment]
Closing as there is nothing actionable here/not our fault
