### ISSUE TITLE
Generating a Call Graph from LLVM IR?

### ISSUE THREAD

**Issue by danleh** [gwsystems/aWsm#97]
Hi everyone!

First, thanks a lot for the cool project and making the source code of your research public! :-)

I have a question regarding using aWsm not for executing Wasm binaries, but for program analysis. In particular, I was wondering if you have tested lifting WebAssembly binaries to LLVM IR with aWsm, and then analyzing that LLVM IR with standard analysis passes.

E.g., we tried obtaining a callgraph of a Wasm binary by first compiling with `awsm binary.wasm -o bitcode.bc` and then running `llvm-opt bitcode.bc --dot-callgraph` on aWsm's LLVM IR output. However, the produced call graph is missing edges for indirect calls. I know it is not the original use case of aWsm, but since you know Wasm and LLVM well, I wanted to ask anyway:
1. Can aWsm generate a call graph for WebAssembly binaries somehow?
2. Do you know why the LLVM --dot-callgraph analysis produces a call graph with missing edges for indirect calls? Is there a better LLVM call graph analysis that could work on your produced bitcode?
3. Do you know of another way for getting a static call graph for WebAssembly binaries?

Thanks again and all the best!

**Comment by gparmer** [comment]
Thanks for the question and interest! We saw Wasabi in the past, so thank you for doing some great research.

We haven't used any of the LLVM analysis facilities. We'd love to hear your experiences, and are welcome to PRs if you find that any provide value.

The indirect calls are added to the indirect call table (https://github.com/gwsystems/aWsm/blob/master/runtime/runtime.c#L25-L28) and retrieved from the table in a specific runtime (https://github.com/gwsystems/aWsm/blob/11704bb706bb73995d08149b72dd478852400c5e/runtime/memory/generic.c#L152-L160 for the generic bounds-check runtime). As such, an edge to an indirect call should be generated every time the LLVM calls `get_function_from_table`. As all indirect functions are filtered through these indirections, I'm not too surprised that LLVM IR passes lose some information about the functions.

Is LLVM normally able of generating *complete* callgraphs for C programs (from LLVM IR, of course) with indirect function calls? Generally, I assumed that this wasn't possible. If such an analysis is type-directed, our cast of the function pointers to `void *` while performing our own type checks (https://github.com/gwsystems/aWsm/blob/master/runtime/runtime.h#L159) might be prohibiting that.

**Comment by danleh** [comment]
Thanks a lot for the super quick answer!

> Is LLVM normally able of generating complete callgraphs for C programs (from LLVM IR, of course) with indirect function calls?

That's a good question. I don't know. We had naively hoped the `--dot-callgraph` pass is sound, but maybe not precise (i.e., overapproximates the call graph a lot). As I understand you, that is not the case, so we will have to look into LLVM call graph analyses a bit more. In case a student of yours knows how to get sound LLVM call graphs, we would be very interested in that (or other ways of getting static call graphs for Wasm).

Thanks also for the pointer to `get_function_from_table`. Interestingly, while it returns the function pointer as a `void *`, the generated LLVM IR for a `call_indirect` instruction then bitcasts it to the correct Wasm type. So conceivably, a smart analysis could still use that to subset the call targets by type (but evidently `--dot-callgraph` does not).

Anyways, I think you answered my question, so feel free to close!

**Comment by gparmer** [comment]
Great! If you figure out more about the LLVM capabilities for this, we'd love to learn more. Very much appreciate if you post here. For the time being, we appreciate your thoughts!
